import { Link, Navigate } from "react-router-dom";
import { useSubscriptionStatus } from "../../../hooks/user/subscription/check-plan-status";
import { useHealthMetrics } from "../../../hooks/user/use-healthMetrics";
import { UserFooter } from "../../../layout/client/ClientFooter";
import { UserHeader } from "../../../layout/client/ClientHeader";
import { GlobalLoader } from "../../../shared/GlobalLoader";
import PremiumDashboardPage from "./PremiumDashboardPage";
import { useActiveAds } from "../../../hooks/user/advertisement/use-active-advertisement";
import { AdCarousel } from "../../../components/user/AdCarousel";
import { Zap, Utensils, Users, Target } from "lucide-react";
import { FeatureCard } from "../../../components/user/FeatureCard";
const DEFAULT_AD = {
  brandName: "Fitora Fitness AI",
  brandLink: "/subscription",
  description: "Experience the future of fitness with AI-driven workouts, smart nutrition, and expert guidance tailored just for you.",
  bannerImages: [
    "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80", // High-quality gym background
    "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&q=80", 
    "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&q=80"
  ]
};
export default function HomePage() {
const { data: metrics, isLoading: isMetricsLoading } = useHealthMetrics();
const { data: subData, isLoading: isSubLoading } = useSubscriptionStatus();
const { data: adData, isLoading: isAdLoading } = useActiveAds();
  if (isMetricsLoading || isSubLoading || isAdLoading) return <GlobalLoader />;

  if (subData?.isPremium && metrics?.exists === false) {
    return <Navigate to="/health-metrics" replace />;
  }
  const hasPremium = !!subData?.isPremium;
const activeAd = adData?.advertisement?.[0] || DEFAULT_AD;
const FEATURES = [
  {
    title: "AI Workout Plans",
    description: "Personalized routines generated by AI based on your body metrics and fitness goals.",
    icon: Zap,
    gradient: "bg-[#00ff94]"
  },
  {
    title: "Smart Diet Scheduling",
    description: "AI-driven meal plans that calculate macros and calories specifically for your transformation.",
    icon: Utensils,
    gradient: "bg-blue-500"
  },
  {
    title: "Expert Trainers",
    description: "Connect with certified professionals for 1-on-1 sessions and specialized training programs.",
    icon: Users,
    gradient: "bg-purple-500"
  },
  {
    title: "Progress Tracking",
    description: "Visualize your journey with advanced health metrics and real-time performance analytics.",
    icon: Target,
    gradient: "bg-orange-500"
  }
];

  return (
   <div className="min-h-screen bg-[#0d1f17] text-white flex flex-col font-sans">
      <UserHeader />
      <main className="flex-1 pt-20">
        {hasPremium ? (
          <div className="max-w-7xl mx-auto px-6 py-12 animate-in fade-in duration-700">
             <PremiumDashboardPage />
          </div>
        ) : (
          <div className="animate-in slide-in-from-bottom-4 duration-700">
            <section className="max-w-7xl mx-auto px-6 py-12">
              {/* Dynamic Advertisement Carousel */}
              {activeAd ? (
                <AdCarousel ad={activeAd} />
              ) : (
                /* Fallback if no ads are active */
                <div className="relative rounded-[2.5rem] bg-gradient-to-br from-[#132a1e] to-[#0d1f17] border border-white/5 p-12 overflow-hidden flex items-center min-h-[450px]">
                   <h1 className="text-4xl font-black italic uppercase text-white/20">Fitora Fitness</h1>
                </div>
              )}
            </section>
            <section className="max-w-7xl mx-auto px-6 py-20">
              <div className="text-center mb-16">
                <span className="text-[#00ff94] text-[10px] font-black uppercase italic tracking-[0.3em]">The Fitora Edge</span>
                <h2 className="text-5xl font-black italic uppercase tracking-tighter mt-4">Why Choose Us?</h2>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                {FEATURES.map((feature, index) => (
                  <FeatureCard key={index} {...feature} />
                ))}
              </div>
            </section>

            <section className="max-w-7xl mx-auto px-6 py-20 text-center">
                <h2 className="text-5xl font-black italic uppercase tracking-tighter mb-12">Try our premium version</h2>
                <Link to="/subscription">
                    <button className="bg-[#00ff94] text-[#0d1f17] px-10 py-5 rounded-2xl font-black uppercase italic text-sm hover:scale-105 transition-transform">
                      View Pricing Plans
                    </button>
                </Link>
            </section>
          </div>
        )}
      </main>
      <UserFooter />
    </div>
  );
}