export enum NotificationType {
  SLOT_CREATED = "SLOT_CREATED",
  SLOT_BOOKED = "SLOT_BOOKED",
  SLOT_CANCELLED = "SLOT_CANCELLED",
  PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
  SUBSCRIPTION_ACTIVE = "SUBSCRIPTION_ACTIVE",
  SYSTEM_ALERT = "SYSTEM_ALERT",
  SUBSCRIPTION_CANCEL="SUBSCRIPTION_CANCEL",
  WALLET_CREDITED = "WALLET_CREDITED"
}


